// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vStZs4oovvtk4EJiDhWZhg
// Component: BhwuH-8AbnR9

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdSteps } from "@plasmicpkgs/antd5/skinny/registerSteps";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: vStZs4oovvtk4EJiDhWZhg/projectcss
import sty from "./PlasmicStepper.module.css"; // plasmic-import: BhwuH-8AbnR9/css

createPlasmicElementProxy;

export type PlasmicStepper__VariantMembers = {};
export type PlasmicStepper__VariantsArgs = {};
type VariantPropType = keyof PlasmicStepper__VariantsArgs;
export const PlasmicStepper__VariantProps = new Array<VariantPropType>();

export type PlasmicStepper__ArgsType = {
  dotStyle?: boolean;
};
type ArgPropType = keyof PlasmicStepper__ArgsType;
export const PlasmicStepper__ArgProps = new Array<ArgPropType>("dotStyle");

export type PlasmicStepper__OverridesType = {
  steps?: Flex__<typeof AntdSteps>;
};

export interface DefaultStepperProps {
  dotStyle?: boolean;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStepper__RenderFunc(props: {
  variants: PlasmicStepper__VariantsArgs;
  args: PlasmicStepper__ArgsType;
  overrides: PlasmicStepper__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "steps.current",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <AntdSteps
      data-plasmic-name={"steps"}
      data-plasmic-override={overrides.steps}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.steps
      )}
      current={generateStateValueProp($state, ["steps", "current"])}
      items={(() => {
        const __composite = [
          { title: null, description: null, status: null },
          { title: null, description: null, disabled: null, status: null },
          { title: null, description: null, status: null },
          { title: null, description: null, status: null }
        ];
        __composite["0"]["title"] = "Exterior";
        __composite["0"]["description"] = "Select exterior options";
        __composite["0"]["status"] = "process";
        __composite["1"]["title"] = "1st Floor";
        __composite["1"]["description"] = "Make selections on the 1st floor";
        __composite["1"]["disabled"] = false;
        __composite["1"]["status"] = "error";
        __composite["2"]["title"] = "2nd Floor";
        __composite["2"]["description"] = "Make selections for the 2nd floor";
        __composite["2"]["status"] = "finish";
        __composite["3"]["title"] = "Review";
        __composite["3"]["description"] = "Let's review your selections";
        __composite["3"]["status"] = "wait";
        return __composite;
      })()}
      onChange={generateStateOnChangeProp($state, ["steps", "current"])}
      percent={60}
      responsive={true}
      size={"default"}
      status={"wait"}
      type={"default"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  steps: ["steps"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  steps: typeof AntdSteps;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStepper__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStepper__VariantsArgs;
    args?: PlasmicStepper__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStepper__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStepper__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStepper__ArgProps,
          internalVariantPropNames: PlasmicStepper__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStepper__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "steps") {
    func.displayName = "PlasmicStepper";
  } else {
    func.displayName = `PlasmicStepper.${nodeName}`;
  }
  return func;
}

export const PlasmicStepper = Object.assign(
  // Top-level PlasmicStepper renders the root element
  makeNodeComponent("steps"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicStepper
    internalVariantProps: PlasmicStepper__VariantProps,
    internalArgProps: PlasmicStepper__ArgProps
  }
);

export default PlasmicStepper;
/* prettier-ignore-end */
